services:
  db:
    image: mysql:8.0
    container_name: app_db1
    environment:
      MYSQL_DATABASE: app_db1
      MYSQL_USER: app_user1
      MYSQL_PASSWORD: app_pass1
      MYSQL_ROOT_PASSWORD: root1
    ports:
      - "3308:3306"
    volumes:
      - dbdata:/var/lib/mysql

  app:
    build:
      context: ./evidencije_laravel
      dockerfile: ../docker/laravel/Dockerfile
    container_name: app_laravel1
    working_dir: /var/www
    volumes:
      - ./evidencije_laravel:/var/www
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: app_nginx1
    ports:
      - "8080:80"
    volumes:
      - ./evidencije_laravel:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  front:
    image: node:20-alpine
    container_name: app_front1
    working_dir: /app
    volumes:
      - ./evidencije_react:/app
    ports:
      - "5173:5173"
      - "3000:3000"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

volumes:
  dbdata: 